# Generated by Django 4.2.5 on 2023-10-11 08:43

import admin_brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.PositiveIntegerField(default=admin_brand.models.generate_id, unique=True)),
                ('brand_img', models.ImageField(blank=True, null=True, upload_to='brand')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
